services:
  gf-demos:
    image: gf-demos
    ports:
      - 8199:8199

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306

volumes:
  mysql-data: