class           系统用户类{
    String 用户名;
    String 密码;
    void 登录系统();
    void 核对验证码();
}
class           问卷类{
    String 问卷说明;
    void 添加问卷说明();
    void 发布问卷();
    void 生成问卷网址();
    void 生成问卷二维码();
    void 查看问卷答卷();
    void 生成统计分析报表();
}


class           受调查者类{
    String 用户名;
    void 填写问卷();
}

class          客服中心类{
    void 在线咨询();
    
    void 接收用户反馈意();
}

class 问卷题目类{
    单选题;
    多选题;
    单项填空;
    多项填空;
    单行文本简;
}
系统用户类 "1" *-- "many" 问卷类 : 包含
问卷类 "1" *-- "many"  问卷题目类: 包含
受调查者类 -- 问卷类 : > 回答
系统用户类 -- 客服中心类 : > 咨询